services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
      - /app/node_modules # Empêche le partage des node_modules entre hôte et conteneur
    environment:
      - NODE_ENV=development
    command: npm run start

  postgres:
    image: postgres:latest
    container_name: mydatabase
    restart: always
    ports:
      - "5466:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: